"""
tools/report_tools.py — Custom tools for the Report Agent.

Tools:
    - compile_report:  Assembles the full patient report from state data.
    - save_report:     Persists the report to a timestamped local text file.
"""

from __future__ import annotations

import os
from datetime import datetime
from pathlib import Path
from typing import List, Optional


_REPORT_DIR = Path("reports")
_REPORT_DIR.mkdir(exist_ok=True)

_DISCLAIMER = (
    "\n⚠️  DISCLAIMER: This report is generated by an AI-assisted triage system "
    "for informational purposes only. It does NOT constitute medical advice, "
    "diagnosis, or treatment. Always consult a qualified healthcare professional."
)


def compile_report(
    patient_id: str,
    raw_symptoms: str,
    structured_symptoms: List[str],
    severity_score: int,
    symptom_analysis: str,
    possible_conditions: List[str],
    research_summary: str,
    red_flags: List[str],
    triage_level: str,
    triage_reasoning: str,
    triage_advice: str,
) -> str:
    """
    Assemble a structured patient triage report from all agent outputs.

    The report is formatted for human readability and includes all
    reasoning from each agent in the pipeline.

    Args:
        patient_id:          Unique patient identifier.
        raw_symptoms:        Original free-text entered by the patient.
        structured_symptoms: Normalised symptom list from Symptom Agent.
        severity_score:      Numeric severity (1–10) from Symptom Agent.
        symptom_analysis:    LLM narrative from Symptom Agent.
        possible_conditions: Differential diagnosis list from Research Agent.
        research_summary:    Evidence-based summary from Research Agent.
        red_flags:           Emergency warnings from Research Agent.
        triage_level:        Urgency tier from Triage Agent.
        triage_reasoning:    Reasoning string from Triage Agent.
        triage_advice:       Patient-facing advice from Triage Agent.

    Returns:
        A fully formatted multi-section report string.

    Raises:
        ValueError: If patient_id is empty.

    Example:
        >>> report = compile_report("P001", "fever and cough", ...)
        >>> assert "PATIENT TRIAGE REPORT" in report
    """
    if not patient_id or not patient_id.strip():
        raise ValueError("patient_id must not be empty.")

    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    sep = "=" * 60

    sections = [
        f"{sep}",
        f"        PATIENT TRIAGE REPORT",
        f"{sep}",
        f"Patient ID  : {patient_id}",
        f"Generated   : {timestamp}",
        f"Triage Level: [{triage_level}]",
        f"{sep}",
        "",
        "─── SECTION 1: SYMPTOM ANALYSIS ───────────────────────────",
        f"Raw Input    : {raw_symptoms}",
        f"Normalised   : {', '.join(structured_symptoms)}",
        f"Severity     : {severity_score}/10",
        "",
        "Agent Analysis:",
        symptom_analysis,
        "",
        "─── SECTION 2: RESEARCH & DIFFERENTIAL DIAGNOSIS ──────────",
        "Possible Conditions (ranked by evidence):",
        *[f"  {i+1}. {c}" for i, c in enumerate(possible_conditions)],
        "",
        "Evidence Summary:",
        research_summary,
        "",
    ]

    if red_flags:
        sections += [
            "─── ⚠️  RED FLAGS DETECTED ─────────────────────────────────",
            *red_flags,
            "",
        ]

    sections += [
        "─── SECTION 3: TRIAGE DECISION ─────────────────────────────",
        f"Triage Level : {triage_level}",
        f"Reasoning    : {triage_reasoning}",
        "",
        "Recommended Action:",
        triage_advice,
        "",
        sep,
        _DISCLAIMER,
        sep,
    ]

    return "\n".join(sections)


def save_report(report_text: str, patient_id: str) -> str:
    """
    Save the compiled report to a timestamped file in the reports/ directory.

    Args:
        report_text: Full report string from compile_report().
        patient_id:  Used to name the file for easy retrieval.

    Returns:
        Absolute path string of the saved file.

    Raises:
        IOError: If the file cannot be written.

    Example:
        >>> path = save_report(report, "P001")
        >>> assert path.endswith(".txt")
    """
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    filename = f"report_{patient_id}_{timestamp}.txt"
    filepath = _REPORT_DIR / filename

    try:
        filepath.write_text(report_text, encoding="utf-8")
    except OSError as exc:
        raise IOError(f"Failed to write report to {filepath}: {exc}") from exc

    return str(filepath.resolve())